/*
 * @Author: ZhangZhen
 * @Date: 2021-11-05 11:33:51
 * @LastEditTime: 2022-01-24 12:45:58
 * @LastEditors: ZhangZhen
 * @Description: In User Settings Edit
 * @FilePath: \ss-cibs-prc-inmpc\nodejs_cibs-prc-inmpc\src\configs\keys.js
 */

/** request-token */
const TOKEN = 'token';
/** head */
const HEAD = 'head';
/** storage-tabs */
const STORAGE_TABS = 'STORAGE_TABS';

/** 2022-01-24 new-params */
const DISCOUNT_REQUEST_PARAMS = 'DISCOUNT_REQUEST_PARAMS';
const BUSINESS_START_REQUEST_PARAMS = 'BUSINESS_START_REQUEST_PARAMS';
const QOUTA_REQUEST_PARAMS = 'QOUTA_REQUEST_PARAMS';
const EPSBUSINESS_REQUEST_PARAMS = 'EPSBUSINESS_REQUEST_PARAMS';
const MERCHAINTS_MAINTAIN_REQUEST_PARAMS = 'MERCHAINTS_MAINTAIN_REQUEST_PARAMS';
const ANNOUNCEMENT_REQUEST_PARAMS = 'ANNOUNCEMENT_REQUEST_PARAMS';
const EXCEPTION_REQUEST_PARAMS = 'EXCEPTION_REQUEST_PARAMS';
/** 2022-01-24 new-params */

export {
  TOKEN,
  HEAD,
  STORAGE_TABS,
  DISCOUNT_REQUEST_PARAMS,
  BUSINESS_START_REQUEST_PARAMS,
  QOUTA_REQUEST_PARAMS,
  EPSBUSINESS_REQUEST_PARAMS,
  MERCHAINTS_MAINTAIN_REQUEST_PARAMS,
  ANNOUNCEMENT_REQUEST_PARAMS,
  EXCEPTION_REQUEST_PARAMS,
};
