// 授权接口汇总
// 用于处理接口返回参数问题
// 此项目前端封装接口返回 只获取了body,head统一报错
// 因此,在授权类接口会出现  成功的值在(03,60,90,91)body内,而错误的值在head(业务类错误-- 如姓名重复这类)中,
// 故对授权接口进行统一处理
const AuthUrl= ["/payment/innerBank/authExecInterBankTx",
"/userManagement/delelteOperatorAuth",
"/openDeposit/openDepositAuth",
"/orderPay/orderPayTranAuth",
"/elecStatements/updateElecStateAuth",
"/openDeposit/appointAuth",
"/payment/chats/authExecChatsTx",
"/payment/fps/authExecFPSTx",
"/userManagement/updateSecretAuth",
"/bthTran/batchPaydayAuth",
"/userManagement/updateOperatorAuth",
"/corpbank/auth-trade-auth-setting/addAuthTradeAuthSettingAuth",
"/customerAccountManagement/updateBindStatusAuth",
"/setServiceQuota/updateQuotaInfoAuth",
"/payment/telegraphic/authExecTelegraphicTx",
"/orderPay/subscribePayCancelAuth",
"/setUpSmallTransfer/setUpSmallTransferAuth",
"/bthTran/batchTransferAuth",
"/schedule/updateScheduleDateAuth",
"/fund/fundSubscriptionAuth",
"/claimChequeBook/chequeBookAuth",
"/openDeposit/updateInstructionsDetails",
"/elecAuthorization/haveApprovalUpdateAuth",
"/corpbank/auth-template/saveInBankManageAuth",
"/orderPay/saveMyMerchantAuth",
"/elecAuthorization/operationTransaAuth",
"/unify-auth/action",
"/foreignExchange/currencyExchangeAuth",
"/corpbank/auth-template/delAuthTemplateAuth",
"/FPSAccountBinding/fpsAccountBindingAuth",
"/fund/fundChangeAuth",
"/orderPay/subscribePayModifyAuth",
"/FPSAccountBinding/fpsAccountUnbindingAuth",
"/orderPay/deleteMyMerchantAuth",
"/setTransaction/setTransactionPromptAuth",
"/userManagement/saveOperatorAuth",
"/corpbank/auth-template/updateAuthTemplateAuth",
"/setServiceQuota/queryAuthDetails",
"/customerAccountManagement/saveRegisteredAccountAuth",
"/userManagement/updateStatusAuth",
"/fund/fundRedeemAuth",
"/orderPay/updateMyMerchantAuth"]

export default AuthUrl;